In [1]:
import os
import nsdget
from PIL import Image
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use("dark_background")

DATA_DIR = os.path.join("..", "data")

In [5]:
df = nsdget.df_stimuli_info(DATA_DIR)
df.head()

,cocoId,cocoSplit,cropBox,loss,nsdId,flagged,BOLD5000,shared1000,subject1,subject2,...,subject5_rep2,subject6_rep0,subject6_rep1,subject6_rep2,subject7_rep0,subject7_rep1,subject7_rep2,subject8_rep0,subject8_rep1,subject8_rep2
0,532481,val2017,"[0.0, 0.0, 0.1671875, 0.1671875]",0.100000,0,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
1,245764,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,1,False,False,False,0,0,...,0,0,0,0,13985,14176,28603,0,0,0
2,385029,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,2,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
3,311303,val2017,"[0.0, 0.0, 0.16640625, 0.16640625]",0.125000,3,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,393226,val2017,"[0.0, 0.0, 0.125, 0.125]",0.133333,4,False,False,False,0,0,...,0,13720,22861,23023,0,0,0,0,0,0

In [4]:
tdf = nsdget.unroll_stimuli_trials(df)
tdf.head()

100%|██████████| 73000/73000 [00:07<00:00, 9193.54it/s]

                   cocoId  cocoSplit                             cropBox  \
subjectId trialId
1         1        412922  train2017            [0.0, 0.0, 0.125, 0.125]
          2        474858  train2017  [0.0, 0.0, 0.16640625, 0.16640625]
          3        320696    val2017  [0.0, 0.0, 0.16640625, 0.16640625]
          4        234676  train2017  [0.0, 0.0, 0.16640625, 0.16640625]
          5        301595  train2017            [0.125, 0.125, 0.0, 0.0]

                       loss  nsdId  flagged  BOLD5000  shared1000
subjectId trialId
1         1        0.071429  46002    False      True        True
          2        0.130435  61882    False     False       False
          3        0.000000    828    False     False       False
          4        0.000000  67573    False     False       False
          5        0.000000  16020    False     False       False