In [1]:
import os
import nsdget

nsdget.DATA_DIR = os.path.join("..", "data")

In [2]:
df = nsdget.df_stimuli_info()
df.head()

,cocoId,cocoSplit,cropBox,loss,nsdId,flagged,BOLD5000,shared1000,subject1,subject2,...,subject5_rep2,subject6_rep0,subject6_rep1,subject6_rep2,subject7_rep0,subject7_rep1,subject7_rep2,subject8_rep0,subject8_rep1,subject8_rep2
0,532481,val2017,"[0.0, 0.0, 0.1671875, 0.1671875]",0.100000,0,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
1,245764,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,1,False,False,False,0,0,...,0,0,0,0,13985,14176,28603,0,0,0
2,385029,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,2,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
3,311303,val2017,"[0.0, 0.0, 0.16640625, 0.16640625]",0.125000,3,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,393226,val2017,"[0.0, 0.0, 0.125, 0.125]",0.133333,4,False,False,False,0,0,...,0,13720,22861,23023,0,0,0,0,0,0

In [3]:
subset = df[:10]
subset

,cocoId,cocoSplit,cropBox,loss,nsdId,flagged,BOLD5000,shared1000,subject1,subject2,...,subject5_rep2,subject6_rep0,subject6_rep1,subject6_rep2,subject7_rep0,subject7_rep1,subject7_rep2,subject8_rep0,subject8_rep1,subject8_rep2
0,532481,val2017,"[0.0, 0.0, 0.1671875, 0.1671875]",0.100000,0,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
1,245764,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,1,False,False,False,0,0,...,0,0,0,0,13985,14176,28603,0,0,0
2,385029,val2017,"[0.0, 0.0, 0.125, 0.125]",0.000000,2,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
3,311303,val2017,"[0.0, 0.0, 0.16640625, 0.16640625]",0.125000,3,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,393226,val2017,"[0.0, 0.0, 0.125, 0.125]",0.133333,4,False,False,False,0,0,...,0,13720,22861,23023,0,0,0,0,0,0
5,475150,val2017,"[0.0, 0.0, 0.16640625, 0.16640625]",0.000000,5,False,False,False,0,1,...,0,0,0,0,0,0,0,0,0,0
6,554328,val2017,"[0.0, 0.0, 0.11015625, 0.11015625]",0.000000,6,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7,438269,val2017,"[0.16484375, 0.16484375, 0.0, 0.0]",0.000000,7,False,False,False,0,0,...,0,0,0,0,0,0,0,11767,19544,29069
8,8211,val2017,"[0.0, 0.0, 0.14140625, 0.14140625]",0.000000,8,False,False,False,0,0,...,22809,0,0,0,0,0,0,0,0,0
9,327701,val2017,"[0.0, 0.0, 0.165625, 0.165625]",0.000000,9,False,False,False,0,0,...,0,0,0,0,0,0,0,13481,17352,25765

In [4]:
nsdget.coco_download_links_given(subset["cocoId"], subset["cocoSplit"])

['http://images.cocodataset.org/val2017/000000532481.jpg',
 'http://images.cocodataset.org/val2017/000000245764.jpg',
 'http://images.cocodataset.org/val2017/000000385029.jpg',
 'http://images.cocodataset.org/val2017/000000311303.jpg',
 'http://images.cocodataset.org/val2017/000000393226.jpg',
 'http://images.cocodataset.org/val2017/000000475150.jpg',
 'http://images.cocodataset.org/val2017/000000554328.jpg',
 'http://images.cocodataset.org/val2017/000000438269.jpg',
 'http://images.cocodataset.org/val2017/000000008211.jpg',
 'http://images.cocodataset.org/val2017/000000327701.jpg']